---
title: "R Notebook"
output: html_notebook
---
```{r}
library(mosaic)
library(mosaicCalc)
library(pracma)
library(MASS)
library(Ryacas)
```
Differentiate
```{r}
const = 1
f = D((1 - e^(-8*x)) ~ x)
A = const * f(x=2)

f
A
fractions(A)
```
Integrate
```{r}
const = 1
f = antiD(exp((1-x)/2) ~ x)
limits = c(1, Inf)

f
A = const * (f(x=limits[2]) - f(x=limits[1]))
A
fractions(A)
fun <- function(x) exp((1-x)/2)
integrate(fun, lower=1,upper=Inf)
3/8
```
Double integration
```{r}
fun <- function(x, y) (x*(1-y))
xlimits = c(0,1)
ylimits = c(0,1)

A = integral2(fun, xlimits[1], xlimits[2], ylimits[1], ylimits[2])
A$Q
fractions(A$Q)
```
```{r}
as_r(yac_str("Simplify((2*x^3/2-2*x^3/3)-(x*(x-1)^2/2-(x-1)^3/3)-(x*(x+1)^2/2-(x+1)^3/3))"))
```
continuous marginal distribution at y = yval
```{r}
yval = 0.5
const = 8/7
f = antiD((x*y) ~ x)
xlimits = c(0, 1)

f
A = const * (f(x=xlimits[2], y=yval) - f(x=xlimits[1], y=yval))
cat("fy(",yval,"):\n")
A
fractions(A)
```
continuous marginal distribution at x = xval
```{r}
xval = 4/5
const = 24
f = antiD((x*y) ~ y)
ylimits = c(0, 1)

f
A = const * (f(x=xval, y=ylimits[2]) - f(x=xval, y=ylimits[1]))
cat("fx(",xval,"):\n")
A
fractions(A)
```

```{r}
fractions(4^3/3)
```

